# The block you want to open the shop GUI
# Shop GUI will be activated only by left or right click
shopBlock: 'minecraft:barrel'

# The block you want to open the stock GUI
# Stock GUI will be activated only by left clicking
stockBlock: 'minecraft:composter'

# Allows the use of shop blocks. Setting to false will disable players using specified shop block to open shop GUI
# WARNING: Setting to false will allow breaking of existing shop blocks without deleting shop!
enableShopBlock: true

# Allows the use of stock blocks. Setting to false will disable players using specified stock block to open stock GUI
enableStockBlock: true

# This enables admin shops that don't need stock. Created by typing /shop adminshop, requires ishop.admin permission
enableAdminShop: true

# Allows players to access the stock GUI by typing /shop stock
# Players with ishop.stock permission will bypass if disabled
enableStockCommand: true

# Number of pages to have in the stock GUI
stockPages: 5

# Enable sending of messages when players have purchased or sold item(s) from shops
enableShopNotifications: true

# Enable sending of messages to shop owners if item(s) are out of stock when players try to purchase
enableOutOfStockMessages: true

# Time in seconds before shop owner receives another message about being out of stock when someone tries to buy item(s)
noStockCooldown: 300

# Require player to own at least 1 shop to access stock
mustOwnShopForStock: true

# Amount of money needed to create a shop
# Set to 0 to disable
createCost: 0.0

# Amount of money returned when deleting a shop
# Set to 0 to disable
returnAmount: 0.0

# Amount of days a player is inactive before deleting their shops
# Set to 0 to disable
maxInactiveDays: 0

# Delete block that the shop is located at when deleting a shop
deleteBlock: false

# Show particle effects on active shop blocks
showParticles: true

# Required to set the ishop flag in the regions for it to work
# Only works if WorldGuard is installed
enableWorldGuardFlag: false

# Set whether you want to use permission nodes or not
# Setting to false will allow any player to create a shop up to defaultShopLimit
# Set to true if you have a permission plugin
usePermissions: false

# Only works if usePermissions is set to false
# If it's set to true, then you'll need to edit the limit via permission nodes for example; ishop.create.limit.5
# Set to -1 to disable shop limit
defaultShopLimit: 5

# Allow everyone to remotely manage their own player shops using "/shop manage <id>" command
remoteManage: true

# Allow everyone to use "/shop view <id>" command to view other players shop remotely
remoteShopping: false

# Allow everyone to use "/shop list <player>" command to view full list of given players shops
publicListCommand: false

# Customizable Messages
adminShop: "Admin Shop"
adminShopDisabled: "&cAdmin shops have been disabled!"
broadcastOff: "Broadcast OFF"
broadcastOn: "Broadcast ON"
buy: "&7You bought&a %in &7for&c %out&7!"
buyAction: "BUY"
buyTitle: "PRICE TO BUY ITEMS [SLOT 1]"
buyTitle2: "PRICE TO BUY ITEMS [SLOT 2]"
createShopTitle: "Create shop trades!"
createTitle: "CREATE"
deleteTitle: "DELETE"
disabledShopBlock: "&cCannot create shop location when shop blocks are disabled!"
existingShop: "&cCannot create shop where existing shop is already located!"
foundShops: "&6Found&a %shops &6shop(s) for player:&a %p"
location: "&6Shop&a %id &6location XYZ: "
noItems: "&cYou do not have enough item(s) to buy from this shop!"
noMoney: "&cYou do not have enough money to create a shop! You need at least &o$"
noPermissions: "&cYou do not have permission for this command!"
noPlayerFound: "&cPlayer cannot be found!"
noPlayerShop: "&cPlayer name does not exist! Cannot list player shop!"
noRemoteManage: "&cRemote management of shops has been disabled!"
noRemoteShops: "&cRemote shopping has been disabled!"
normalShop: "&l%player%'s Shop"
noShopFound: "&cNo shop can be found!"
noShopStock: "&cCannot access stock because you do not have any shops!"
noStock: "&cThis shop is currently out of stock of that item(s)!"
noStockNotify: "&cOne of your shops is currently out of stock! &o(%s)"
page: "Page"
playerInventoryFull: "&cYour inventory is FULL! Cannot buy any items!"
playerShopCreated: "&7Shop has been &aCREATED&7 for&a %p &7!"
reload: "&7Configuration file reloaded."
sell: "&7%p has bought&7&c %in &7for&a %out&7!"
sellTitle: "ITEMS FOR SALE [SLOT 1]"
sellTitle2: "ITEMS FOR SALE [SLOT 2]"
shopBusy: "&6Shop is currently busy, try again soon!"
shopCreated: "&7Targeted shop has been &aCREATED&7!"
shopDeleted: "&7Targeted shop has been &cDELETED&7!"
shopIDDeleted: "&cShop id&a %id &chas been DELETED!"
shopIntegerError: "&cShop id must be an integer greater than 0!"
shopLimit: "&cYou do not have permission or have reached your shop limit!"
shopNotOwned: "&cYou do not own this shop!"
stockCommandDisabled: "&cThe /shop stock command has been disabled!"
stockTitle: "Shop Stock Inventory"
targetMismatch: "&cTargeted block must match set shop block!"
clickManage: "&6MANAGE"
clickShop: "&6SHOP"
listAdminShop: "&6Listing all found admin shops:"
manageText: "&6Manage this shop!"
noAdminShopsFound: "&cNo admin shops have been found!"
noShopBlock: "&cshopBlock cannot be empty! Reverting to default minecraft:barrel"
noStockBlock: "&cstockBlock cannot be empty! Reverting to default minecraft:composter"
notPlayer: "&cOnly players in the game can use shop commands!"
shopText: "&6Remotely shop here!"

# Do not edit this!
configVersion: 2.0